# Generated by Django 4.2.4 on 2023-08-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.IntegerField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('Horror', 'Horror'), ('comedy', 'Comedy'), ('sciencefiction', 'Science fiction'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('animation', 'Animation'), ('war', 'War')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('file', models.FileField(upload_to='movies')),
            ],
        ),
    ]
