# Generated by Django 4.2.4 on 2023-09-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_backvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='file',
        ),
    ]
