# Generated by Django 4.2.4 on 2023-09-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_movie_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.movie')),
            ],
        ),
    ]
