# Generated by Django 4.2.4 on 2023-09-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='status',
            field=models.CharField(default='watch_list', max_length=100),
        ),
    ]
