# Generated by Django 4.2.4 on 2023-09-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_watchlist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('backvideo_file', models.FileField(upload_to='backvideos')),
            ],
        ),
    ]
